# Numpy 특징
- 일반 List에 비해 빠르고 메로리 효율적
- 반복문 없이 데이터 배열에 대한 처리를 지원
- 선형대수와 관련된 다양한 기능 제공
- c , c++, 포트란 등의 언어와 통합가능
- 큰 장점이자 List와 가장 큰 차이점 : Dynamic typing not supported

## ndarray : 넘파이에서 가장 기본 단위 

In [8]:
# 넘파이 호출
import numpy as np
# string , int 타입으로 써도 float 타입 명시했기때문에 flat 타입으로 호출
test_array = np.array(['1','2',3,4],float)
test_array, test_array.dtype

(array([1., 2., 3., 4.]), dtype('float64'))

## shape : numpy array의 object와 dimension 구성을 반환함
- ndim : 차원의 크기
- size : data의 개수

In [11]:
test_array = np.array([['1','2',3,4]])
test_array.shape

(1, 4)

In [17]:
#reshape 데이터를 펴줄때 사용
# -1size를 기반으로 row 개수 선정
matrix = [[1,2,3,4],[5,6,7,8]]
np.array(matrix).reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [24]:
# flatten다차원 array를 1차원 array로 변환
matrix = [[1,2,3,4],[5,6,7,8],[2,3,8,9]]
np.array(matrix).flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 2, 3, 8, 9])

In [30]:
a = np.array([[2,3,8,5,10],[6,7,9,4,8]])
a[:,2:] #row는 전체 column은 2열 이상
a[1:,1:] #1row , 1column 이상
a[1,:3] # 1번째 row에서 3번째 cloumn 미만

array([6, 7, 9])

# arange

In [41]:
#arange,reshape 을 활용해 0-29까지 5column의 배열만들기 
np.arange(30).reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [44]:
np.arange(0,10,0.5) #start, end 포인트 설정 후 일정간격으로 정렬가능

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [47]:
# zeros : 0으로 가득찬 ndarray 생성 -> np.zeros(shape, dtype, order)
np.zeros(shape=(10,), dtype=np.int8)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [50]:
# np.ones((2,5)) ones : 1로 가득찬 array 생성
matrix = np.arange(30).reshape(-1,6)
np.ones_like(matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

# axis
- axis = 1 : column
- axis = 0 : row

In [55]:
test = np.arange(12).reshape(3,4)
test

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
test.sum(axis=1), test.sum(axis=0)

(array([ 6, 22, 38]), array([12, 15, 18, 21]))

# concatenate
- Numpy array를 합치는 함수
- vstack, hstack

In [59]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.vstack((a,b))

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([1, 2, 3, 4, 5, 6, 7, 8]))

In [62]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,8],[2,3]])
np.hstack((a,b))

array([[1, 2, 5, 8],
       [3, 4, 2, 3]])

# 사칙연산도 굉장히 간단하게 지원함

In [69]:
test1 = np.array([[1,2,3],[4,5,6]],float)

In [73]:
test1+test1, test1-test1, test1*test1

(array([[ 2.,  4.,  6.],
        [ 8., 10., 12.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[ 1.,  4.,  9.],
        [16., 25., 36.]]))

## dot : matrix의 값이 다를때 곱셈사용

In [79]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(1,7).reshape(3,2)
test_a,test_b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [77]:
test_a.dot(test_b)

array([[22, 28],
       [49, 64]])

# broadcasting : 상당히 중요

- shape이 다른 배열 간 연산을 지원하는 기능
- matrix - scalar
- matrix * scalar
- matrix / scalar
- matrix // scalar
- matrix ** scalar

In [84]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
test_a-1,test_a+1, test_a/2

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[2, 3, 4],
        [5, 6, 7]]),
 array([[0.5, 1. , 1.5],
        [2. , 2.5, 3. ]]))

# comparisons

In [88]:
a = np.arange(10)
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [97]:
# any 1개라도 만족하면 true
np.any(a>5),  np.any(a>9)

(True, False)

In [90]:
# np.where : index값 반환
np.where(a>5)

(array([6, 7, 8, 9], dtype=int64),)

# boolean index

In [104]:
A= np.arange(100)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [102]:
B= A <30
B.astype(int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])